// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApeyAyzG_tIUm5tXid_AMB66Jgk4TMi4w',
    appId: '1:843204760308:web:51679cb00ed9b55b8904a1',
    messagingSenderId: '843204760308',
    projectId: 'cvsangregorio-fe288',
    authDomain: 'cvsangregorio-fe288.firebaseapp.com',
    storageBucket: 'cvsangregorio-fe288.firebasestorage.app',
    measurementId: 'G-5G6421BVVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv2wak7sPTG82fguU8-M6_UISqA2akz8E',
    appId: '1:843204760308:android:f2ecc0192ddedb098904a1',
    messagingSenderId: '843204760308',
    projectId: 'cvsangregorio-fe288',
    storageBucket: 'cvsangregorio-fe288.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP4qJ7JgG_fxHnk4vG81sg2WRdvN-yCFw',
    appId: '1:843204760308:ios:4fb0a5e5fb369f878904a1',
    messagingSenderId: '843204760308',
    projectId: 'cvsangregorio-fe288',
    storageBucket: 'cvsangregorio-fe288.firebasestorage.app',
    iosBundleId: 'com.example.volleyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP4qJ7JgG_fxHnk4vG81sg2WRdvN-yCFw',
    appId: '1:843204760308:ios:4fb0a5e5fb369f878904a1',
    messagingSenderId: '843204760308',
    projectId: 'cvsangregorio-fe288',
    storageBucket: 'cvsangregorio-fe288.firebasestorage.app',
    iosBundleId: 'com.example.volleyTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApeyAyzG_tIUm5tXid_AMB66Jgk4TMi4w',
    appId: '1:843204760308:web:d64b889ca46cbcb78904a1',
    messagingSenderId: '843204760308',
    projectId: 'cvsangregorio-fe288',
    authDomain: 'cvsangregorio-fe288.firebaseapp.com',
    storageBucket: 'cvsangregorio-fe288.firebasestorage.app',
    measurementId: 'G-K5CJ6VGHKQ',
  );
}
